dbshost:
  dbs-url: 'http://ht7.dbsv4.jd.com/ws/fmSwitchInter/'


# mysql connect configuration
mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'test'
  username: 'root'
  password: '1qazx@WSX'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false

sqlcommons:
    gtidcommons:
      mastercommons:
        - "stop master"
        - "stop slave"
        - "reset slave all"
      slavecommons:
        - "reset master"
        - "grant replication slave on *.* to '%s'@'%' IDENTIFIED BY PASSWORD '%s'"
        - "stop slave"
        - "reset slave"
        - "reset master"
        - "change master to master_host='%s', master_user='replicater', master_password='%s', master_port=3358, master_auto_position=1"
        - "start slave"
        - "set global read_only=1"
    fileposcommons:
        mastercommons:
          - "stop master"
          - "stop slave"
          - "reset slave all"
        slavecommons:
          - "reset master"
          - "grant replication slave on *.* to '%s'@'%' IDENTIFIED BY PASSWORD '%s'"
          - "stop slave"
          - "reset slave"
          - "reset master"
          - "change master to master_host='%s', master_user='replicater', master_password='$password', master_port=3358, master_log_file='mysql-bin.000001', master_log_pos=&s, MASTER_CONNECT_RETRY=10;"
          - "start slave"
          - "set global read_only=1"